name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  MFEM_INSTALL: $HOME/.local/mfem

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
      - uses: actions/checkout@v3

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build

      - name: Clone & install MFEM
        run: |
          git clone --depth 1 https://github.com/mfem/mfem.git
          mkdir -p mfem/build && cd mfem/build
          cmake \
            -DCMAKE_INSTALL_PREFIX=$MFEM_INSTALL \
            -DCMAKE_BUILD_TYPE=Release \
            -DMFEM_USE_MPI=OFF \
            ..
          cmake --build . --target install -- -j$(nproc)

      - name: Configure GenDiL
        run: |
          cmake -B build -S . \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} \
            -DUSE_MFEM=ON \
            -DMFEM_DIR=$MFEM_INSTALL/lib/cmake/mfem

      - name: Build
        run: cmake --build build -- -j$(nproc)

      - name: Run tests
        run: cmake --build build --target test

      - name: Run clang-tidy
        if: matrix.compiler == 'clang'
        run: |
          cd build
          run-clang-tidy -p .
